from __future__ import annotations

from copy import deepcopy


INITIAL_STATE = {
    "tickets": [
        {
            "id": 1048,
            "user_id": "sara@lunaatelier.pk",
            "name": "Sara Khan",
            "request_type": "New Project",
            "details": "Need three custom formal outfits for a bridal party with pastel embroidery options.",
            "budget": "PKR 180,000",
            "timeline": "Final fitting needed before June 14",
            "status": "reviewed",
            "notes": "Promising lead. Send pastel mood board and fitting slots.",
            "created_at": "2026-05-25T09:10:00Z",
            "updated_at": "2026-05-25T11:35:00Z",
        },
        {
            "id": 1047,
            "user_id": "bilal@northviewrealty.pk",
            "name": "Bilal Ahmed",
            "request_type": "Appointment",
            "details": "Requested a Friday property viewing for a three-bedroom apartment in DHA.",
            "budget": "PKR 32M ceiling",
            "timeline": "This Friday after 3pm",
            "status": "new",
            "notes": "",
            "created_at": "2026-05-25T08:25:00Z",
            "updated_at": "2026-05-25T08:25:00Z",
        },
        {
            "id": 1046,
            "user_id": "mariam@seasidecatering.pk",
            "name": "Mariam Faisal",
            "request_type": "Inquiry",
            "details": "Asked for buffet pricing for a 120-person mehndi event with vegetarian options.",
            "budget": "Still deciding",
            "timeline": "Event is in early July",
            "status": "actioned",
            "notes": "Quote draft is ready. Waiting on final menu confirmation.",
            "created_at": "2026-05-24T13:15:00Z",
            "updated_at": "2026-05-25T10:05:00Z",
        },
        {
            "id": 1045,
            "user_id": "salman@coolairservices.pk",
            "name": "Salman Ali",
            "request_type": "Complaint",
            "details": "Reported a repeat AC breakdown after a recent service visit and wants urgent follow-up.",
            "budget": "Covered under service warranty",
            "timeline": "Needs a technician today before 6pm",
            "status": "new",
            "notes": "Escalate if no technician is assigned by noon.",
            "created_at": "2026-05-24T07:40:00Z",
            "updated_at": "2026-05-24T09:05:00Z",
        },
        {
            "id": 1044,
            "user_id": "amna@brightpathclinic.pk",
            "name": "Amna Yousaf",
            "request_type": "Meeting",
            "details": "Requested a strategy call about automating patient inquiry intake across WhatsApp and website chat.",
            "budget": "Open to a custom plan",
            "timeline": "Would like to meet next week",
            "status": "closed",
            "notes": "Converted to signed pilot. Moved to onboarding.",
            "created_at": "2026-05-23T15:30:00Z",
            "updated_at": "2026-05-24T16:20:00Z",
        },
    ],
    "events": [
        {
            "id": 5012,
            "source": "admin",
            "event_type": "ticket_updated",
            "status": "info",
            "summary": "Ticket #1048 status changed from new to reviewed.",
            "user_id": "sara@lunaatelier.pk",
            "ticket_id": 1048,
            "request_id": None,
            "payload": {
                "status_changed": True,
                "previous_status": "new",
                "current_status": "reviewed",
                "notes_updated": True,
            },
            "created_at": "2026-05-25T11:35:00Z",
        },
        {
            "id": 5011,
            "source": "email",
            "event_type": "ticket_created",
            "status": "success",
            "summary": "Ticket #1047 created from email conversation.",
            "user_id": "bilal@northviewrealty.pk",
            "ticket_id": 1047,
            "request_id": None,
            "payload": {"subject": "Need to schedule a property viewing"},
            "created_at": "2026-05-25T08:25:00Z",
        },
        {
            "id": 5010,
            "source": "whatsapp",
            "event_type": "ticket_created",
            "status": "success",
            "summary": "Ticket #1046 created from WhatsApp conversation.",
            "user_id": "mariam@seasidecatering.pk",
            "ticket_id": 1046,
            "request_id": None,
            "payload": {"recipient": "operations@seasidecatering.pk"},
            "created_at": "2026-05-24T13:15:00Z",
        },
        {
            "id": 5009,
            "source": "admin",
            "event_type": "ticket_updated",
            "status": "info",
            "summary": "Admin notes updated for ticket #1045.",
            "user_id": "salman@coolairservices.pk",
            "ticket_id": 1045,
            "request_id": None,
            "payload": {"status_changed": False, "notes_updated": True},
            "created_at": "2026-05-24T09:05:00Z",
        },
        {
            "id": 5008,
            "source": "whatsapp",
            "event_type": "extraction_followup",
            "status": "warning",
            "summary": "WhatsApp conversation needed one more clarification before logging.",
            "user_id": "amna@brightpathclinic.pk",
            "ticket_id": None,
            "request_id": None,
            "payload": {"missing_fields": ["timeline"]},
            "created_at": "2026-05-23T15:05:00Z",
        },
    ],
    "sessions_by_user_id": {
        "sara@lunaatelier.pk": {
            "status": "ok",
            "user_id": "sara@lunaatelier.pk",
            "ticket_created": True,
            "turn_count": 6,
            "created_at": "2026-05-25T09:02:00Z",
            "updated_at": "2026-05-25T09:10:00Z",
            "messages": [
                {"role": "user", "content": "Hi, I need three custom outfits for a bridal party next month."},
                {"role": "assistant", "content": "Happy to help. What name should I put on the request?"},
                {"role": "user", "content": "Sara Khan."},
                {"role": "assistant", "content": "Thanks, Sara. Do you already have a budget range in mind for the full set?"},
                {"role": "user", "content": "Around 180,000 rupees, and I need the final fitting before June 14."},
                {"role": "assistant", "content": "Perfect, I have everything I need. Your request has been logged and the team will follow up shortly."},
            ],
        },
        "bilal@northviewrealty.pk": {
            "status": "ok",
            "user_id": "bilal@northviewrealty.pk",
            "ticket_created": True,
            "turn_count": 6,
            "created_at": "2026-05-25T08:18:00Z",
            "updated_at": "2026-05-25T08:25:00Z",
            "messages": [
                {"role": "user", "content": "I want to book a viewing for a three-bedroom apartment in DHA."},
                {"role": "assistant", "content": "Absolutely. What name should we attach to the viewing request?"},
                {"role": "user", "content": "Bilal Ahmed."},
                {"role": "assistant", "content": "Thanks, Bilal. When would you ideally like to visit?"},
                {"role": "user", "content": "This Friday after 3pm. Budget is around 32 million."},
                {"role": "assistant", "content": "Great, your viewing request is in. The team will confirm the next steps shortly."},
            ],
        },
        "mariam@seasidecatering.pk": {
            "status": "ok",
            "user_id": "mariam@seasidecatering.pk",
            "ticket_created": True,
            "turn_count": 8,
            "created_at": "2026-05-24T12:50:00Z",
            "updated_at": "2026-05-24T13:15:00Z",
            "messages": [
                {"role": "user", "content": "Can you quote catering for a mehndi of around 120 guests?"},
                {"role": "assistant", "content": "Of course. What name should I note on the request?"},
                {"role": "user", "content": "Mariam Faisal."},
                {"role": "assistant", "content": "Thanks. Is this mainly a buffet setup, plated dinner, or something else?"},
                {"role": "user", "content": "Buffet, and we need vegetarian options too."},
                {"role": "assistant", "content": "Noted. Do you have a budget range or event timing in mind yet?"},
                {"role": "user", "content": "Still deciding the budget, but it will be in early July."},
                {"role": "assistant", "content": "That is enough for us to log it. The team will send menu options and pricing guidance shortly."},
            ],
        },
    },
}


def clone_initial_state() -> dict:
    return deepcopy(INITIAL_STATE)
